version: '3'

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./public:/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  php:
    build: .
    volumes:
      - ./public:/html
      - ./private:/private
  mysql:
    image: mysql:5
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kloboard
      MYSQL_USER: kloboard
      MYSQL_PASSWORD: kloboard
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOST=mysql
     - PMA_USER=root
     - PMA_PASSWORD=root
    restart: always
    ports:
     - 8000:80
